/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor.clases;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JSeparator;
import javax.swing.JRadioButtonMenuItem;
import java.awt.Window.Type;

/**
 *
 * @author Yo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	setResizable(false);
    	setType(Type.UTILITY);
    	setTitle("Gestor Comercial");
    	setSize(800,800);
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        panelContenedor = new javax.swing.JTabbedPane();
        panelCompra = new javax.swing.JPanel();
        panelInventario = new javax.swing.JPanel();
        lblNombreProducto_Inventario = new javax.swing.JLabel();
        lblNombreProducto_Inventario.setBounds(20, 30, 92, 14);
        tfNombreProducto_Inventario = new javax.swing.JTextField();
        tfNombreProducto_Inventario.setBounds(112, 27, 95, 20);
        btnConsultarProducto_Inventario = new javax.swing.JButton();
        btnConsultarProducto_Inventario.setBounds(217, 26, 79, 23);
        jScrollPaneInventario = new javax.swing.JScrollPane();
        jScrollPaneInventario.setBounds(20, 60, 359, 129);
        jTableInventario = new javax.swing.JTable();
        panelContabilidad = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        panelVenta = new javax.swing.JPanel();
        jScrollPaneVenta = new javax.swing.JScrollPane();
        jScrollPaneVenta.setBounds(24, 125, 343, 123);
        jTableVenta = new javax.swing.JTable();
        lblIdProducto_Venta = new javax.swing.JLabel();
        lblIdProducto_Venta.setBounds(22, 33, 73, 17);
        tfIdProducto_Venta = new javax.swing.JTextField();
        tfIdProducto_Venta.setBounds(91, 33, 67, 20);
        lblCantidad_Venta = new javax.swing.JLabel();
        lblCantidad_Venta.setBounds(24, 53, 47, 14);
        tfCantidad_Venta = new javax.swing.JTextField();
        tfCantidad_Venta.setBounds(91, 53, 67, 20);
        lblProductosAVender = new javax.swing.JLabel();
        lblProductosAVender.setBounds(24, 112, 98, 14);
        btnAgregarProducto_Venta = new javax.swing.JButton();
        btnAgregarProducto_Venta.setBounds(24, 73, 134, 23);
        btnRealizarVenta = new javax.swing.JButton();
        btnRealizarVenta.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        btnRealizarVenta.setBounds(24, 249, 115, 23);
        
                jTableVenta.setModel(new DefaultTableModel(
                	new Object[][] {
                		{null, null, null, null},
                		{null, null, null, null},
                		{null, null, null, null},
                		{null, null, null, null},
                		{null, null, null, null},
                		{null, null, null, null},
                	},
                	new String[] {
                		"Producto", "Cantidad", "Precio Unitario", "Precio Total"
                	}
                ));
                jTableVenta.getColumnModel().getColumn(2).setPreferredWidth(88);
                jScrollPaneVenta.setViewportView(jTableVenta);
                
                        lblIdProducto_Venta.setText("Id producto:");
                        
                                tfIdProducto_Venta.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jTextField1ActionPerformed(evt);
                                    }
                                });
                                
                                        lblCantidad_Venta.setText("Cantidad:");
                                        
                                                tfCantidad_Venta.addActionListener(new java.awt.event.ActionListener() {
                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                        jTextField2ActionPerformed(evt);
                                                    }
                                                });
                                                
                                                        lblProductosAVender.setText("Productos a vender:");
                                                        
                                                                btnAgregarProducto_Venta.setText("Agregar producto");
                                                                btnAgregarProducto_Venta.addActionListener(new java.awt.event.ActionListener() {
                                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                        jButton1ActionPerformed(evt);
                                                                    }
                                                                });
                                                                
                                                                        btnRealizarVenta.setText("Realizar venta");
                                                                        
                                                                        JLabel lblIdVenta = new JLabel();
                                                                        lblIdVenta.setBounds(24, 14, 47, 14);
                                                                        lblIdVenta.setText("Id venta:");
                                                                        
                                                                                panelContenedor.addTab("Venta", panelVenta);
                                                                                panelVenta.setLayout(null);
                                                                                panelVenta.add(lblIdVenta);
                                                                                panelVenta.add(lblIdProducto_Venta);
                                                                                panelVenta.add(tfIdProducto_Venta);
                                                                                panelVenta.add(lblCantidad_Venta);
                                                                                panelVenta.add(tfCantidad_Venta);
                                                                                panelVenta.add(lblProductosAVender);
                                                                                panelVenta.add(jScrollPaneVenta);
                                                                                panelVenta.add(btnAgregarProducto_Venta);
                                                                                panelVenta.add(btnRealizarVenta);
                                                                                
                                                                                JLabel lblMuestraElId_Venta = new JLabel("'muestra el id'");
                                                                                lblMuestraElId_Venta.setBounds(81, 14, 67, 14);
                                                                                panelVenta.add(lblMuestraElId_Venta);
                                                                                
                                                                                JLabel lblregistraElCliente = new JLabel("'registra el cliente'");
                                                                                lblregistraElCliente.setBounds(286, 14, 94, 14);
                                                                                panelVenta.add(lblregistraElCliente);
                                                                                
                                                                                JLabel lblNombreCliente = new JLabel();
                                                                                lblNombreCliente.setBounds(197, 14, 79, 14);
                                                                                lblNombreCliente.setText("Nombre cliente:");
                                                                                panelVenta.add(lblNombreCliente);
                                                                                
                                                                                JLabel lblNombreProducto_Venta = new JLabel();
                                                                                lblNombreProducto_Venta.setText("Nombre producto");
                                                                                lblNombreProducto_Venta.setBounds(197, 36, 94, 14);
                                                                                panelVenta.add(lblNombreProducto_Venta);
                                                                                
                                                                                tfNombreProducto_Venta = new JTextField();
                                                                                tfNombreProducto_Venta.setBounds(286, 33, 94, 20);
                                                                                panelVenta.add(tfNombreProducto_Venta);
                                                                                
                                                                                JButton btnBuscarProducto_Venta = new JButton();
                                                                                btnBuscarProducto_Venta.addActionListener(new ActionListener() {
                                                                                	public void actionPerformed(ActionEvent e) {
                                                                                	}
                                                                                });
                                                                                btnBuscarProducto_Venta.setText("Buscar producto");
                                                                                btnBuscarProducto_Venta.setBounds(203, 55, 134, 23);
                                                                                panelVenta.add(btnBuscarProducto_Venta);
                                                                                
                                                                                tfValorTotal = new JTextField();
                                                                                tfValorTotal.setBounds(270, 249, 97, 20);
                                                                                panelVenta.add(tfValorTotal);
                                                                                
                                                                                JLabel lblValorTotal = new JLabel();
                                                                                lblValorTotal.setText("Valor total:");
                                                                                lblValorTotal.setBounds(205, 251, 61, 17);
                                                                                panelVenta.add(lblValorTotal);
        
        JLabel lblIdCompra_Compra = new JLabel();
        lblIdCompra_Compra.setBounds(20, 14, 71, 14);
        lblIdCompra_Compra.setText("Id compra:");
        
        JLabel lblMuestraElId_Compra = new JLabel("'muestra el id'");
        lblMuestraElId_Compra.setBounds(87, 14, 67, 14);
        
        JLabel lblNombreProveedor_Compra = new JLabel();
        lblNombreProveedor_Compra.setBounds(193, 14, 94, 14);
        lblNombreProveedor_Compra.setText("Nombre proveedor:");
        
        JLabel lblregistraElProveedor_Compra = new JLabel("'registra el proveedor'");
        lblregistraElProveedor_Compra.setBounds(297, 14, 94, 14);
        
        JLabel lblIdProducto_Compra = new JLabel();
        lblIdProducto_Compra.setBounds(20, 35, 73, 17);
        lblIdProducto_Compra.setText("Id producto:");
        
        tfIdProducto_Compra = new JTextField();
        tfIdProducto_Compra.setBounds(87, 33, 67, 20);
        
        JLabel lblNombreProducto_Compra = new JLabel();
        lblNombreProducto_Compra.setBounds(193, 36, 94, 14);
        lblNombreProducto_Compra.setText("Nombre producto");
        
        tfNombreProducto_Compra = new JTextField();
        tfNombreProducto_Compra.setBounds(282, 33, 94, 20);
        
        JButton btnBuscarProducto_Compra = new JButton();
        btnBuscarProducto_Compra.setBounds(203, 61, 134, 23);
        btnBuscarProducto_Compra.setText("Buscar producto");
        
        tfCantidad_Compra = new JTextField();
        tfCantidad_Compra.setBounds(87, 53, 67, 20);
        
        JLabel lblCantidad_Compra = new JLabel();
        lblCantidad_Compra.setBounds(20, 53, 47, 14);
        lblCantidad_Compra.setText("Cantidad:");
        
        JButton btnAgregarProducto_Compra = new JButton();
        btnAgregarProducto_Compra.setBounds(20, 73, 134, 23);
        btnAgregarProducto_Compra.setText("Agregar producto");
        
        JLabel lblProductosAComprar_Compra = new JLabel();
        lblProductosAComprar_Compra.setBounds(20, 112, 134, 14);
        lblProductosAComprar_Compra.setText("Productos a comprar:");
        
        JButton btnRealizarCompra = new JButton();
        btnRealizarCompra.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btnRealizarCompra.setBounds(276, 103, 115, 23);
        btnRealizarCompra.setText("Realizar compra");

        panelContenedor.addTab("Compra", panelCompra);
        panelCompra.setLayout(null);
        panelCompra.add(lblIdCompra_Compra);
        panelCompra.add(lblMuestraElId_Compra);
        panelCompra.add(lblNombreProveedor_Compra);
        panelCompra.add(lblregistraElProveedor_Compra);
        panelCompra.add(lblIdProducto_Compra);
        panelCompra.add(tfIdProducto_Compra);
        panelCompra.add(lblNombreProducto_Compra);
        panelCompra.add(tfNombreProducto_Compra);
        panelCompra.add(lblCantidad_Compra);
        panelCompra.add(tfCantidad_Compra);
        panelCompra.add(btnAgregarProducto_Compra);
        panelCompra.add(btnBuscarProducto_Compra);
        panelCompra.add(lblProductosAComprar_Compra);
        panelCompra.add(btnRealizarCompra);
        
        jScrollPaneCompra = new JScrollPane();
        jScrollPaneCompra.setBounds(20, 127, 356, 111);
        panelCompra.add(jScrollPaneCompra);
        
        jTableCompra = new JTable();
        jTableCompra.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null},
        	},
        	new String[] {
        		"Producto", "Cantidad", "Precio Unitario", "Precio Total"
        	}
        ));
        jTableCompra.getColumnModel().getColumn(2).setPreferredWidth(86);
        jTableCompra.getColumnModel().getColumn(3).setPreferredWidth(80);
        jScrollPaneCompra.setViewportView(jTableCompra);
        
        tfValorTotal_Compra = new JTextField();
        tfValorTotal_Compra.setBounds(76, 241, 97, 20);
        panelCompra.add(tfValorTotal_Compra);
        
        lblValorTotal_Compra = new JLabel();
        lblValorTotal_Compra.setText("Valor total:");
        lblValorTotal_Compra.setBounds(20, 243, 61, 17);
        panelCompra.add(lblValorTotal_Compra);
        
        tfValorCancelado_Compra = new JTextField();
        tfValorCancelado_Compra.setBounds(279, 241, 97, 20);
        panelCompra.add(tfValorCancelado_Compra);
        
        lblValorCancelado_Compra = new JLabel();
        lblValorCancelado_Compra.setText("Valor cancelado:");
        lblValorCancelado_Compra.setBounds(199, 243, 88, 17);
        panelCompra.add(lblValorCancelado_Compra);

        lblNombreProducto_Inventario.setText("Nombre producto:");

        tfNombreProducto_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        btnConsultarProducto_Inventario.setText("Consultar");

        jTableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Laboratorio", "Vencimiento", "Precio", "Existencias"
            }
        ));
        jScrollPaneInventario.setViewportView(jTableInventario);

        panelContenedor.addTab("Inventario", panelInventario);
        panelInventario.setLayout(null);
        panelInventario.add(lblNombreProducto_Inventario);
        panelInventario.add(tfNombreProducto_Inventario);
        panelInventario.add(btnConsultarProducto_Inventario);
        panelInventario.add(jScrollPaneInventario);
        
        JButton btnProductosAVencerse = new JButton("Productos a vencerse");
        btnProductosAVencerse.setBounds(20, 195, 137, 23);
        panelInventario.add(btnProductosAVencerse);
        
        JButton btnProductosAAcabarse = new JButton("Productos a acabarse");
        btnProductosAAcabarse.setBounds(20, 229, 137, 23);
        panelInventario.add(btnProductosAAcabarse);

        jLabel12.setText("Generar informe:");

        jButton6.setText("Informe del día");

        jButton7.setText("Informe de la semana");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Informe del mes");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel13.setText("Cuentas por pagar:");

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha de compra", "Proveedor", "Valor"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        javax.swing.GroupLayout gl_panelContabilidad = new javax.swing.GroupLayout(panelContabilidad);
        panelContabilidad.setLayout(gl_panelContabilidad);
        gl_panelContabilidad.setHorizontalGroup(
            gl_panelContabilidad.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panelContabilidad.createSequentialGroup()
                .addGroup(gl_panelContabilidad.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_panelContabilidad.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(gl_panelContabilidad.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)))
                    .addGroup(gl_panelContabilidad.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(gl_panelContabilidad.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_panelContabilidad.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        gl_panelContabilidad.setVerticalGroup(
            gl_panelContabilidad.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panelContabilidad.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        panelContenedor.addTab("Contabilidad", panelContabilidad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor)
        );

        pack();
        
        JMenuBar barraMenuPrincipal = new JMenuBar();
        setJMenuBar(barraMenuPrincipal);
        
        JMenu menuArchivo = new JMenu("Archivo");
        barraMenuPrincipal.add(menuArchivo);
        
        JMenuItem menuCerrarSesion = new JMenuItem("Cerrar sesi\u00F3n");
        menuArchivo.add(menuCerrarSesion);
        
        JMenuItem menuSalir = new JMenuItem("Salir");
        menuArchivo.add(menuSalir);
        
        JMenu menuCrear = new JMenu("Crear");
        barraMenuPrincipal.add(menuCrear);
        
        JMenuItem menuNuevoAdministrador = new JMenuItem("Nuevo administrador");
        menuCrear.add(menuNuevoAdministrador);
        
        JMenuItem menuNuevoVendedor = new JMenuItem("Nuevo vendedor");
        menuCrear.add(menuNuevoVendedor);
        
        JMenuItem menuNuevoCliente = new JMenuItem("Nuevo cliente");
        menuCrear.add(menuNuevoCliente);
        
        JMenuItem menuNuevoProveedor = new JMenuItem("Nuevo proveedor");
        menuCrear.add(menuNuevoProveedor);
        
        JSeparator separatorCrear = new JSeparator();
        menuCrear.add(separatorCrear);
        
        JMenuItem menuNuevoProducto = new JMenuItem("Nuevo producto");
        menuCrear.add(menuNuevoProducto);
        
        JMenu menuModificar = new JMenu("Modificar");
        barraMenuPrincipal.add(menuModificar);
        
        JMenuItem menuModAdministrador = new JMenuItem("Administrador");
        menuModificar.add(menuModAdministrador);
        
        JMenuItem menuModVendedor = new JMenuItem("Vendedor");
        menuModificar.add(menuModVendedor);
        
        JMenuItem menuModCliente = new JMenuItem("Cliente");
        menuModificar.add(menuModCliente);
        
        JMenuItem menuModProveedor = new JMenuItem("Proveedor");
        menuModificar.add(menuModProveedor);
        
        JSeparator separatorModificar = new JSeparator();
        menuModificar.add(separatorModificar);
        
        JMenuItem menuModProducto = new JMenuItem("Producto");
        menuModificar.add(menuModProducto);
        
        JMenu menuInhabilitar = new JMenu("Inhabilitar");
        barraMenuPrincipal.add(menuInhabilitar);
        
        JMenuItem menuInAdministrador = new JMenuItem("Administrador");
        menuInhabilitar.add(menuInAdministrador);
        
        JMenuItem menuInVendedor = new JMenuItem("Vendedor");
        menuInhabilitar.add(menuInVendedor);
        
        JMenuItem menuInCliente = new JMenuItem("Cliente");
        menuInhabilitar.add(menuInCliente);
        
        JMenuItem menuInProveedor = new JMenuItem("Proveedor");
        menuInhabilitar.add(menuInProveedor);
        
        JSeparator separatorInhabilitar = new JSeparator();
        menuInhabilitar.add(separatorInhabilitar);
        
        JMenuItem menuInProducto = new JMenuItem("Producto");
        menuInhabilitar.add(menuInProducto);
        
        JMenu menuAyuda = new JMenu("Ayuda");
        barraMenuPrincipal.add(menuAyuda);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto_Venta;
    private javax.swing.JButton btnRealizarVenta;
    private javax.swing.JButton btnConsultarProducto_Inventario;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblIdProducto_Venta;
    private javax.swing.JLabel lblNombreProducto_Inventario;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel lblCantidad_Venta;
    private javax.swing.JLabel lblProductosAVender;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JPanel panelCompra;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelContabilidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneVenta;
    private javax.swing.JScrollPane jScrollPaneInventario;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane panelContenedor;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableVenta;
    private javax.swing.JTable jTableInventario;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField tfIdProducto_Venta;
    private javax.swing.JTextField tfCantidad_Venta;
    private javax.swing.JTextField tfNombreProducto_Inventario;
    private JTextField tfNombreProducto_Venta;
    private JTextField tfIdProducto_Compra;
    private JTextField tfNombreProducto_Compra;
    private JTextField tfCantidad_Compra;
    private JScrollPane jScrollPaneCompra;
    private JTable jTableCompra;
    private JTextField tfValorTotal;
    private JTextField tfValorTotal_Compra;
    private JLabel lblValorTotal_Compra;
    private JTextField tfValorCancelado_Compra;
    private JLabel lblValorCancelado_Compra;
}
